name: .NET Core

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.1
      with:
        # 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Path to lcov file
        path-to-lcov: ./tests/Oceana.Core.Tests/TestResults/coverage.info
        # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
        #parallel: false # optional
        # Set to true for the last action when using "parallel: true".
        #parallel-finished: false # optional
        # Coveralls Enterprise server (more info: https://enterprise.coveralls.io)
        #coveralls-endpoint: # optional, default is https://coveralls.io
        # The root folder of the project that originally ran the tests
        #base-path: # optional
