name: Build

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Oceana.Core Coverage
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: coverage-core
        path-to-lcov: ./tests/Oceana.Core.Tests/TestResults/coverage.info
        parallel: true
    - name: Oceana.Abstractions Coverage
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: coverage-abstractions
        path-to-lcov: ./tests/Oceana.Abstractions.Tests/TestResults/coverage.info
        parallel: true
    - name: Coverage Complete
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
