name: .NET Core

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        # User defined upload name. Visible in Codecov UI
        name: Oceana.Core Results
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: 00e8b62d-b1f4-40a9-8457-1b6718801526
        # Path to coverage file to upload
        file: tests/Oceana.Core.Tests/TestResults/coverage.info
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests # optional
        # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
        # env_vars: # optional
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
